### ISSUE TITLE
missing item sets

### ISSUE THREAD

**Issue by eyegouch** [Ilshidur/LoL-item-sets#16]
currently only 94 of the 140 champions have generated their item sets
i tried the Windows app and the zip file

**Comment by Ilshidur** [comment]
Apparently, this bug occurs since Thurday 3rd May 2018 :

![image](https://user-images.githubusercontent.com/6564012/39941393-b6091ff8-555c-11e8-8dae-01038618b2b0.png)

[This has been already reported](https://github.com/league-of-legends-devs/LoL-item-sets/issues/14) but at the moment I can't find a way to fix this. I'll keep this issue opened until I find a workaround.

My apologies for the inconvenience. Stay tuned :wink:

**Comment by Ilshidur** [comment]
This bug is fixed. You can now download all the item sets from the website or from the application.

The bug was introduced by a [silly mistake on my end](https://github.com/league-of-legends-devs/feeder.lol-item-sets-generator.org/commit/c1aabafc5c1cc25a914ab50d00bc83ce793717c2), sorry.

Let me know if you have suggestions or anything else :-)
Closing this issue and https://github.com/league-of-legends-devs/LoL-item-sets/issues/17 as they are related.
