### ISSUE TITLE
Not builds for Quinn for 2 patches

### ISSUE THREAD

**Issue by nizdi** [Ilshidur/LoL-item-sets#17]
Thought this bug was in last patch, but seem like this one is the same (8.11) and quinn is generating no patches. Even champions with less play rate like Volibear and Urgot have builds!

Thanks.

**Comment by Ilshidur** [comment]
Hello and thanks for your report.

This bug is fixed. You can now download all the item sets from the website or from the application.

The bug was introduced by a [silly mistake on my end](https://github.com/league-of-legends-devs/feeder.lol-item-sets-generator.org/commit/c1aabafc5c1cc25a914ab50d00bc83ce793717c2), sorry.

Let me know if you have suggestions or anything else :-)
Closing this issue and https://github.com/league-of-legends-devs/LoL-item-sets/issues/16 as they are related.
