### ISSUE TITLE
Current patch not working

### ISSUE THREAD

**Issue by nizdi** [Ilshidur/LoL-item-sets#18]
I'm not sure it's discontinued, anyway...

**Comment by Ilshidur** [comment]
Hello. Thank you for your report. The project is still up, but I'm working on a full rework on my side.

I don't always watch the state of the patches, but I can confirm that the builds are not generated automatically anymore :

![image](https://user-images.githubusercontent.com/6564012/53111670-d25b8080-353d-11e9-9137-d7c602857cf6.png)

I'll try to fix this today. Stay tuned ;-)

**Comment by Ilshidur** [comment]
OK. I got it to work. Now I have to publish the changes to the current website. I'll do it as soon as possible.

You'll be informed when I've done that.

**Edit :** [Champion.gg seems down](https://api.champion.gg). I'll deploy it when they fix their website.

**Comment by nizdi** [comment]
Thanks!!Waiting here. Love this, thnaks for keep workign on it.

**Comment by Ilshidur** [comment]
Gosh, the API is still not up ... I messaged the guys, but they don't seem to respond.
That's unfortunate because the item sets generator depends on it. And I don't have the time to make my own statistics bot.

**Note : the ["API"](https://api.champion.gg) is a service that provides all the datas from champion.gg to developers, so they can directly use their data instead of creating a bot that will scrap the datas from their website.**

I'll keep waiting, but I don't guarantee this will be up soon ...

If you want to keep using pre-built item sets, here's [**Championify**](https://github.com/dustinblackman/Championify). This app does only crawling through their website and doesn't query the API. Thus, the app still works. They're good guys. You can use it as an alternative until I find a way to fix this 😄 

Sorry again.

**Comment by Baxxster** [comment]
Hello,

Just got a message from Champion.gg on Facebook, the API is now back up and they will release a statement about it soon!

**Comment by Ilshidur** [comment]
I just got the same answer ! I'll have a close eye on the generator to make sure it builds the item sets correctly.

I guess champion.gg will go down, though ...

**EDIT :** the item sets are back up !

**Comment by nizdi** [comment]
Nice!! Thanks for the work and thanks Baxxster for the info.
