### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by piperun** [Ilshidur/LoL-item-sets#19]
Last commit was done in 2018 and since it seems it's using some form of manual parsing you can't just rely on it working seamlessly (i.e. it leaves out any newly added champion after 2018).

**Comment by Ilshidur** [comment]
Hello. The item sets buider (https://github.com/league-of-legends-devs/feeder.lol-item-sets-generator.org) is broken due to the recent Riot API changes.

I need to :

* update the script according to the new API changes
* re-deploy it
* wait for the 24h timeout for the generator to re-build the item sets again

This is why the latest patch version froze to `9.7.1`. This project could be considered in "stand by" instead of "dead".

As this takes a little bit of time, I currently don't have much free time. But, be sure that I did not abandoned this project.

**Comment by piperun** [comment]
Oh, well I hope you continue the project once you got more time!
