### ISSUE TITLE
3/14/16 Unhandled exception issue

### ISSUE THREAD

**Issue by Connocclar** [Ilshidur/LoL-item-sets#3]
> *************\*  Exception Text *************\* 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Lol_item_sets.MainForm.downloadAndInstallSets()
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at MetroFramework.Controls.MetroButton.OnMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> ---

Currently IG is on patch 6.5 but not showing the Game patch in the UI.

**Comment by Ilshidur** [comment]
This issue is happening on every application at the moment.

As the [Twitter status](https://twitter.com/LoL_item_sets/status/709187305194561536) says :
The website is currently being migrated to a new server and the domain name is still not resolvable yet.
Therefore, the service is down until the website is on.

This problem will be fixed soon. Sorry for the inconvenience.

**Comment by Ilshidur** [comment]
**FIXED** : the website is now working again.
