### ISSUE TITLE
Linking issues

### ISSUE THREAD

**Issue by TacetNoxPavor** [Ilshidur/LoL-item-sets#4]
Just letting you know the "Go to Website" option links to 
item-sets-generator.org 
not lol-item-sets-generator.org

as well as the page https://lol-item-sets-generator.org/clicks/click.php?id=access_from_application
throwing a "Link with this ID was not found".

**Comment by Ilshidur** [comment]
Thank you for the feedback. I was aware of this problem.

The fact is that the website used to be named "item-sets-generator.org" and then got renamed to "lol-item-sets-generator.org". The application didn't get an update since that.

I am planning to rewrite a new application from scratch. This one will fix this link issue.

**Comment by Ilshidur** [comment]
**FIXED** : see the [0.2.0 version](https://twitter.com/LoL_item_sets/status/743545035094917121/photo/1).
