### ISSUE TITLE
y u drunk

### ISSUE THREAD

**Issue by L9Sneaky** [Ilshidur/LoL-item-sets#7]
http://puu.sh/rB4Hw.png

**Comment by Ilshidur** [comment]
Thank you for your reporting.

As [this Tweet says](https://twitter.com/LoL_item_sets/status/784487059482374148), the website was providing the wrong Windows app : 0.2.0 instead of 0.3.0.
The older app (0.2.0) is not working anymore and needs to be updated [here](https://lol-item-sets-generator.org/downloads/windows-app-from-website).

**FIXED**
